### PR TITLE
HHH-17460 - Ongoing JPA 32 work

### PR DESCRIPTION
**Pull request by dreab8**
Noticed that in same cases the schema creation does generate the  FKs.

With the default in
`<xs:attribute name="not-found" default="exception" type="NotFoundEnum"/>`

 a `@NotFound` annotation is always created even when the XML mapping does not contain any `not-found` attribute.

### CODE REVIEW

**Comment by sebersole** [comment]
I was just finishing up a rebase from main when you sent this.  Do you mind if I force push and you apply this over that?

**Comment by sebersole** [comment]
I did the forced push.  I'll just pull your branch local and apply it

**Comment by sebersole** [comment]
Cherry-picked on top of the rebase and pushed.  Thanks!

**Comment by dreab8** [comment]
Thanks Steve, I was doing it locally :D

**Pull request closed without merging**
